apiVersion: v1
kind: Service
metadata:
  # This must match the dns name used by Concord in deployment.config
  name: client-1
  labels:
    app: client-1-clientservice
spec:
  type: ClusterIP
  ports:
    - name: '50505'
      port: 50505
      protocol: TCP
      targetPort: 50505
  selector:
    app: client-1-clientservice

