## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageCredentials
##

## @param global.imageCredentials Global Docker image registry
##
global:
  # The credentials for the docker registry. If username/password/email are specified, a corresponding Secret is created.
  imageCredentials:
    registry: ""
    username: |-
      <USERNAME>
    password: |-
      <PASSWORD>
    email: ""
  # The global artifact tag
  image:
    repository: "vmwblockchain/k8s-orchestrator"
    tag: ""

